on: [push, pull_request]

name: ci

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: docker build -t clion-epitech-docker -f Dockerfile .
